### ISSUE TITLE
User can search their entries. Provide a search box that causes the entries list to only show matches.

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/code-journal#9]
## 💰 Motivation

Users will want to search through all of their entries and only view entries that match their search

## 📐 Plan

Only display user's journal entries that fit the search criteria so they only see those entries

## ✅ Task List
- [x] Add a text input to the navbar
- [x] Add a button next to the text input
- [x] Listen for clicks on the search button
- [x] Show the entries view if this search button is clicked
- [x] Look at the text content of each entry in entry list on the DOM tree
- [x] If the value of the search input does not match the value of any of the text content of the entry, set the entry class to hidden
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x]  Fix all errors.
